version: '3'

services:
  relay_alice:
    image: kusama:0.9.5
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - ../chain-specs/kusama-local.json:/kusama.json
    command: polkadot --chain=/kusama.json --base-path /tmp/relay_alice --alice --validator --rpc-methods Unsafe --rpc-cors all --unsafe-ws-external --unsafe-rpc-external --name RelayAlice --node-key 0000000000000000000000000000000000000000000000000000000000000001
    networks:
      docker_testing_net:
        ipv4_address: 172.28.1.1

  relay_bob:
    image: kusama:0.9.5
    depends_on:
      - relay_alice
    volumes:
      - ../chain-specs/kusama-local.json:/kusama.json
    command: polkadot --chain=/kusama.json --bob --validator --base-path /tmp/relay_bob --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp --rpc-cors all
    networks:
      docker_testing_net:
        ipv4_address: 172.28.1.2

  para_alice:
    image: purestake/moonbeam:v0.11.2
    volumes:
      - ../chain-specs/kusama-local.json:/kusama.json
#     "--ethapi=txpool,debug,trace"
    command: "--ethapi=txpool,debug,trace" --collator --alice --chain moonbeam-local --base-path /tmp/para_alice --name "CollatorAlice" --force-authoring --parachain-id 2001 --rpc-cors all --rpc-methods Unsafe --unsafe-ws-external --unsafe-rpc-external --execution native --node-key 0000000000000000000000000000000000000000000000000000000000000001 '-linfo,evm=debug,ethereum=trace,rpc=trace,cumulus_collator=debug,txpool=debug' -- --execution wasm --chain /kusama.json
    networks:
      docker_testing_net:
        ipv4_address: 172.28.2.3

  para_bob:
    image: purestake/moonbeam:v0.11.2
    depends_on:
      - para_alice
    volumes:
      - ../chain-specs/kusama-local.json:/kusama.json
    command: --collator --bob --chain moonbeam-local --base-path /tmp/para_bob --name "CollatorBob" --force-authoring --parachain-id 2001 --rpc-cors all --rpc-methods Unsafe --unsafe-ws-external --unsafe-rpc-external --bootnodes /ip4/172.28.1.3/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp -- --execution wasm --chain /kusama.json --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    networks:
      docker_testing_net:
        ipv4_address: 172.28.2.4

networks:
#  testing_net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
  docker_testing_net:
    external: true
    name: docker_testing_net